#!/usr/bin/env node

/**
 * Build Script for 8th Grade Pre-Algebra Platform
 *
 * This script generates env-inject.js with environment variables
 * injected at build time for the frontend to use.
 */

const fs = require('fs');
const path = require('path');

// Get environment variables
const SUPABASE_URL = process.env.VITE_SUPABASE_URL || '';
const SUPABASE_ANON_KEY = process.env.VITE_SUPABASE_ANON_KEY || '';
const GEMINI_API_KEY = process.env.VITE_GEMINI_API_KEY || '';

// Validate required variables
if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  console.error('❌ Missing required environment variables:');
  if (!SUPABASE_URL) console.error('  - VITE_SUPABASE_URL');
  if (!SUPABASE_ANON_KEY) console.error('  - VITE_SUPABASE_ANON_KEY');
  process.exit(1);
}

// Generate env-inject.js content
const envInjectContent = `/**
 * Environment Variables - Auto-generated at build time
 * DO NOT EDIT THIS FILE MANUALLY
 *
 * Generated: ${new Date().toISOString()}
 */

window.ENV = {
  SUPABASE_URL: '${SUPABASE_URL}',
  SUPABASE_ANON_KEY: '${SUPABASE_ANON_KEY}',
  GEMINI_API_KEY: '${GEMINI_API_KEY || ''}',
  NODE_ENV: '${process.env.NODE_ENV || 'production'}'
};

console.log('✅ Environment variables loaded successfully');
`;

// Write env-inject.js
const outputPath = path.join(__dirname, 'env-inject.js');
fs.writeFileSync(outputPath, envInjectContent, 'utf8');

console.log('✅ Build complete!');
console.log(`   Generated: ${outputPath}`);
console.log(`   Supabase URL: ${SUPABASE_URL}`);
console.log(`   Anon Key: ${SUPABASE_ANON_KEY.substring(0, 20)}...`);
