-- ============================================================================
-- Migration: 006_seed_lessons.sql
-- Description: Seed all 87 Pre-Algebra lessons from Q1-Q4 curriculum
-- Created: 2025-01-13
-- Total Lessons: 19
-- ============================================================================

-- Clear existing lessons (if any)
TRUNCATE TABLE public.lessons CASCADE;

-- Insert all lessons
INSERT INTO public.lessons (
  lesson_number,
  date,
  day_type,
  quarter,
  unit_number,
  unit_name,
  standard_code,
  standard_title,
  strand,
  lesson_topic,
  learning_objectives,
  key_vocabulary,
  materials_needed,
  xp_value,
  coin_value,
  cognitive_complexity,
  integrated_mtr_standards,
  status,
  notes
) VALUES
  (1, '2025-09-04', 'B', 'Q1', 1, 'Number Sense and Operations - 8th Grade', 'MA.8.NSO.1.1', 'Extend previous understanding of rational numbers to define irrational numbers within the real number system. Locate an approximate value of a numerical expression involving irrational numbers on a number line.', 'Number Sense and Operations', 'Introduction to Irrational Numbers and the Real Number System', '["Students will distinguish between rational and irrational numbers","Students will understand that irrational numbers have non-terminating, non-repeating decimal representations","Students will recognize pi (π) as an irrational number","Students will create a graphic organizer showing the relationship between subsets of the real number system","Students will understand that every number on the number line is either rational or irrational"]', '["irrational number","rational number","real number","terminating decimal","repeating decimal","non-terminating","non-repeating","pi (π)"]', '["Whiteboard and markers","Calculator","Student notebooks","Real number system graphic organizer template","Pi (π) decimal expansion printout"]', 100, 50, 'Level 2: Basic Application of Skills & Concepts', '["MA.K12.MTR.2.1","MA.K12.MTR.4.1"]', 'NOT CREATED', 'First lesson of 8th grade. Establish strong foundation for irrational numbers. Use visual organizer showing Natural → Whole → Integer → Rational → Real number hierarchy.'),
  (2, '2025-09-08', 'B', 'Q1', 1, 'Number Sense and Operations - 8th Grade', 'MA.8.NSO.1.1', 'Extend previous understanding of rational numbers to define irrational numbers within the real number system. Locate an approximate value of a numerical expression involving irrational numbers on a number line.', 'Number Sense and Operations', 'Approximating Square Roots and Locating Them on a Number Line', '["Students will identify perfect squares from 1 to 225","Students will approximate square roots of non-perfect squares using benchmark perfect squares","Students will locate approximate values of square roots on a number line","Students will use the strategy of finding which perfect squares a number falls between","Students will refine approximations by testing decimal values"]', '["square root","perfect square","approximation","benchmark","radicand","between"]', '["Whiteboard and markers","Calculator (for verification)","Student notebooks","Number lines (0-15)","Perfect squares reference chart (1-225)","Practice worksheet on approximating square roots"]', 100, 50, 'Level 2: Basic Application of Skills & Concepts', '["MA.K12.MTR.2.1","MA.K12.MTR.5.1","MA.K12.MTR.6.1"]', 'NOT CREATED', 'Key strategy: √28 is between √25 and √36, so √28 is between 5 and 6. Since 28 is closer to 25, √28 ≈ 5.3. Build estimation skills without calculator first.'),
  (3, '2025-09-11', 'B', 'Q1', 1, 'Number Sense and Operations - 8th Grade', 'MA.8.NSO.1.1', 'Extend previous understanding of rational numbers to define irrational numbers within the real number system. Locate an approximate value of a numerical expression involving irrational numbers on a number line.', 'Number Sense and Operations', 'Approximating Expressions with Irrational Numbers (Addition and Subtraction)', '["Students will approximate expressions like 1 + √30 by first approximating the irrational number","Students will locate expressions involving addition with square roots on a number line","Students will evaluate expressions like π - 2 and locate them on a number line","Students will understand that adding/subtracting a rational and irrational number yields an irrational number","Students will solve real-world problems involving expressions with irrational numbers"]', '["numerical expression","irrational number","approximation","sum","difference","location on number line"]', '["Whiteboard and markers","Calculator","Student notebooks","Number lines","Practice problems with √ and π expressions"]', 100, 50, 'Level 2: Basic Application of Skills & Concepts', '["MA.K12.MTR.2.1","MA.K12.MTR.4.1","MA.K12.MTR.6.1"]', 'NOT CREATED', 'Example: 1 + √30. First approximate √30 ≈ 5.5, then 1 + 5.5 ≈ 6.5. Emphasize the process of breaking down complex expressions.'),
  (4, '2025-09-15', 'B', 'Q1', 1, 'Number Sense and Operations - 8th Grade', 'MA.8.NSO.1.2', 'Plot, order and compare rational and irrational numbers, represented in various forms.', 'Number Sense and Operations', 'Plotting, Ordering, and Comparing Rational and Irrational Numbers', '["Students will plot rational and irrational numbers on a number line with appropriate scale","Students will order sets of rational and irrational numbers from least to greatest","Students will compare rational and irrational numbers using inequality symbols (<, >, =)","Students will work with numbers in various forms (decimals, fractions, square roots, cube roots)","Students will determine appropriate scales for number lines based on the numbers being plotted"]', '["plot","order","compare","least to greatest","inequality symbols","scale","rational number","irrational number"]', '["Whiteboard and markers","Calculator","Student notebooks","Blank number lines","Mixed number cards (rational and irrational)","Comparison symbol cards"]', 100, 50, 'Level 2: Basic Application of Skills & Concepts', '["MA.K12.MTR.2.1","MA.K12.MTR.4.1","MA.K12.MTR.5.1"]', 'NOT CREATED', 'Include numbers like -3.42857, √50, ∛10, 2.5, π, -√25. Students must approximate irrationals to plot accurately.'),
  (5, '2025-09-18', 'B', 'Q1', 1, 'Number Sense and Operations - 8th Grade', 'MA.8.NSO.1.2', 'Plot, order and compare rational and irrational numbers, represented in various forms.', 'Number Sense and Operations', 'Working with Cube Roots - Plotting and Comparing', '["Students will identify perfect cubes from -125 to 125","Students will approximate cube roots of non-perfect cubes","Students will plot cube roots on a number line","Students will compare and order sets including both square roots and cube roots","Students will recognize that every positive number has one positive and one negative square root, but only one cube root"]', '["cube root","perfect cube","radicand","index","approximation","positive and negative square roots"]', '["Whiteboard and markers","Calculator","Student notebooks","Perfect cubes reference chart (-125 to 125)","Number lines","Practice worksheet with cube roots"]', 100, 50, 'Level 2: Basic Application of Skills & Concepts', '["MA.K12.MTR.2.1","MA.K12.MTR.4.1","MA.K12.MTR.5.1"]', 'NOT CREATED', 'Plot ∛8, ∛10, ∛27 on number line. Perfect cubes: -125, -64, -27, -8, -1, 0, 1, 8, 27, 64, 125. Emphasize difference between square and cube roots.'),
  (6, '2025-09-22', 'B', 'Q1', 1, 'Number Sense and Operations - 8th Grade', 'MA.8.NSO.1.3', 'Extend previous understanding of the Laws of Exponents to include integer exponents. Apply the Laws of Exponents to evaluate numerical expressions and generate equivalent numerical expressions, limited to integer exponents and rational number bases, with procedural fluency.', 'Number Sense and Operations', 'Review of Exponent Laws and Introduction to Negative Integer Exponents', '["Students will review Product Rule, Quotient Rule, and Power Rule from 7th grade","Students will understand that negative exponents represent reciprocals (a^(-n) = 1/a^n)","Students will develop meaning for negative exponents through pattern exploration","Students will simplify expressions with negative exponents","Students will convert between expressions with negative exponents and fractional forms"]', '["integer exponent","negative exponent","reciprocal","power","base","equivalent expressions"]', '["Whiteboard and markers","Calculator","Student notebooks","Pattern exploration worksheet (powers of 2 from 2^3 to 2^(-3))","Laws of Exponents reference sheet (Appendix E)"]', 100, 50, 'Level 2: Basic Application of Skills & Concepts', '["MA.K12.MTR.2.1","MA.K12.MTR.3.1","MA.K12.MTR.5.1"]', 'NOT CREATED', 'Use pattern approach: 2^3=8, 2^2=4, 2^1=2, 2^0=1, 2^(-1)=1/2, 2^(-2)=1/4. Students discover that each step divides by 2, leading to negative exponents as reciprocals.'),
  (7, '2025-09-25', 'B', 'Q1', 1, 'Number Sense and Operations - 8th Grade', 'MA.8.NSO.1.3', 'Extend previous understanding of the Laws of Exponents to include integer exponents. Apply the Laws of Exponents to evaluate numerical expressions and generate equivalent numerical expressions, limited to integer exponents and rational number bases, with procedural fluency.', 'Number Sense and Operations', 'Applying Laws of Exponents with Integer Exponents', '["Students will apply Product Rule with integer exponents: a^m × a^n = a^(m+n)","Students will apply Quotient Rule with integer exponents: a^m ÷ a^n = a^(m-n)","Students will apply Power Rule with integer exponents: (a^m)^n = a^(mn)","Students will simplify complex expressions using multiple exponent laws","Students will evaluate numerical expressions with integer exponents and rational bases with procedural fluency"]', '["product rule","quotient rule","power rule","integer exponents","simplify","equivalent expressions"]', '["Whiteboard and markers","Calculator","Student notebooks","Mixed practice worksheet with integer exponents","Laws of Exponents reference poster"]', 100, 50, 'Level 2: Basic Application of Skills & Concepts', '["MA.K12.MTR.2.1","MA.K12.MTR.3.1","MA.K12.MTR.5.1"]', 'NOT CREATED', 'Example: (2^4)/(2^7) = 2^(-3) = 1/8. Students must be fluent with both positive and negative integer exponents.'),
  (8, '2025-09-29', 'B', 'Q1', 1, 'Number Sense and Operations - 8th Grade', 'MA.8.NSO.1.4', 'Express numbers in scientific notation to represent and approximate very large or very small quantities. Determine how many times larger or smaller one number is compared to a second number.', 'Number Sense and Operations', 'Introduction to Scientific Notation - Converting and Understanding Magnitude', '["Students will understand that scientific notation is a × 10^n where 1 ≤ a < 10 and n is an integer","Students will convert very large numbers to scientific notation (positive exponents)","Students will convert very small numbers to scientific notation (negative exponents)","Students will convert from scientific notation to standard form","Students will recognize calculator notation using ''E'' (e.g., 2.3E27 means 2.3 × 10^27)"]', '["scientific notation","standard form","power of 10","exponent","magnitude","coefficient","very large","very small"]', '["Whiteboard and markers","Scientific calculator","Student notebooks","Place value chart with powers of 10","Real-world data examples (astronomical distances, atomic sizes)","Practice worksheet on converting to/from scientific notation"]', 100, 50, 'Level 2: Basic Application of Skills & Concepts', '["MA.K12.MTR.2.1","MA.K12.MTR.4.1","MA.K12.MTR.5.1"]', 'NOT CREATED', 'Example: 39,900,000,000,000 km to Proxima Centauri = 3.99 × 10^13 km. Bohr radius 0.0000000000529 = 5.29 × 10^(-11). Connect to place value.'),
  (9, '2025-10-02', 'B', 'Q1', 1, 'Number Sense and Operations - 8th Grade', 'MA.8.NSO.1.4', 'Express numbers in scientific notation to represent and approximate very large or very small quantities. Determine how many times larger or smaller one number is compared to a second number.', 'Number Sense and Operations', 'Comparing Numbers in Scientific Notation - Determining Magnitude Differences', '["Students will compare two numbers in scientific notation to determine which is larger or smaller","Students will determine how many times larger one number is compared to another","Students will understand that if the exponent increases by 1, the value increases by a factor of 10","Students will solve problems comparing very large or very small quantities","Students will apply comparison skills to real-world contexts (astronomy, biology, physics)"]', '["times larger","times smaller","magnitude","factor of 10","compare","exponent difference"]', '["Whiteboard and markers","Scientific calculator","Student notebooks","Real-world comparison problems (planet sizes, cell sizes, etc.)","Practice worksheet on comparing scientific notation"]', 100, 50, 'Level 2: Basic Application of Skills & Concepts', '["MA.K12.MTR.2.1","MA.K12.MTR.4.1","MA.K12.MTR.6.1"]', 'NOT CREATED', 'Example: Blue whale 4×10^5 lb vs. elephant 1×10^4 lb. Compare: 4×10^5 is approximately 40 times heavier (4×10 = 40). Oct 2 may be ''No School'' - verify calendar.'),
  (10, '2025-10-06', 'B', 'Q1', 1, 'Number Sense and Operations - 8th Grade', 'MA.8.NSO.1.5', 'Add, subtract, multiply and divide numbers expressed in scientific notation with procedural fluency.', 'Number Sense and Operations', 'Multiplying and Dividing Numbers in Scientific Notation', '["Students will multiply numbers in scientific notation by multiplying coefficients and adding exponents","Students will divide numbers in scientific notation by dividing coefficients and subtracting exponents","Students will ensure final answers are in proper scientific notation form (1 ≤ a < 10)","Students will apply Laws of Exponents to operations with scientific notation","Students will demonstrate procedural fluency with multiplication and division of scientific notation"]', '["multiply","divide","coefficient","exponent","product rule","quotient rule","scientific notation"]', '["Whiteboard and markers","Scientific calculator","Student notebooks","Color highlighters (to separate coefficients and powers of 10)","Practice worksheet on multiplying/dividing scientific notation"]', 100, 50, 'Level 1: Recall', '["MA.K12.MTR.2.1","MA.K12.MTR.5.1"]', 'NOT CREATED', 'Example: (3.2×10^28)(6.7×10^7) = (3.2×6.7)(10^28×10^7) = 21.44×10^35 = 2.144×10^36. Must convert to proper form.'),
  (11, '2025-10-09', 'B', 'Q1', 1, 'Number Sense and Operations - 8th Grade', 'MA.8.NSO.1.5', 'Add, subtract, multiply and divide numbers expressed in scientific notation with procedural fluency.', 'Number Sense and Operations', 'Adding and Subtracting Numbers in Scientific Notation', '["Students will understand that addition/subtraction requires the same power of 10 (like place values)","Students will rewrite numbers in scientific notation with a common exponent before adding/subtracting","Students will add and subtract coefficients when exponents match","Students will ensure final answers are in proper scientific notation form","Students will demonstrate procedural fluency with addition and subtraction (exponents within 2 of each other)"]', '["addition","subtraction","common exponent","same power of 10","rewrite","place value connection"]', '["Whiteboard and markers","Scientific calculator","Student notebooks","Place value connection chart","Practice worksheet on adding/subtracting scientific notation"]', 100, 50, 'Level 1: Recall', '["MA.K12.MTR.2.1","MA.K12.MTR.5.1"]', 'NOT CREATED', 'Example: (2.31×10^15) + (9.1×10^13). Rewrite 9.1×10^13 as 0.091×10^15, then add: 2.31 + 0.091 = 2.401×10^15. Limit to exponents within 2.'),
  (12, '2025-10-14', 'B', 'Q1', 1, 'Number Sense and Operations - 8th Grade', 'MA.8.NSO.1.6', 'Solve real-world problems involving operations with numbers expressed in scientific notation.', 'Number Sense and Operations', 'Real-World Applications of Scientific Notation', '["Students will solve real-world problems involving multiplication and division in scientific notation","Students will understand and apply significant digits rules to answers","Students will interpret results in the context of real-world situations","Students will work with cross-curricular examples from science (astronomy, chemistry, biology)","Students will determine appropriate precision based on significant digits in the problem"]', '["real-world application","significant digits","precision","measurement","scientific context","interpret"]', '["Whiteboard and markers","Scientific calculator","Student notebooks","Real-world problem task cards (astronomy, biology, physics contexts)","Significant digits reference guide"]', 100, 50, 'Level 2: Basic Application of Skills & Concepts', '["MA.K12.MTR.2.1","MA.K12.MTR.4.1","MA.K12.MTR.6.1","MA.K12.MTR.7.1"]', 'NOT CREATED', 'Example: Amazon River releases 5.5×10^7 gal/sec. 3.2×10^9 sec/year. How many gallons/year? Answer: 1.8×10^17 gallons (2 sig figs).'),
  (13, '2025-10-17', 'B', 'Q1', 1, 'Number Sense and Operations - 8th Grade', 'MA.8.NSO.1.6', 'Solve real-world problems involving operations with numbers expressed in scientific notation.', 'Number Sense and Operations', 'Multi-Step Real-World Problems with Scientific Notation and Significant Digits', '["Students will solve multi-step problems involving scientific notation in real-world contexts","Students will apply addition/subtraction with scientific notation to real problems","Students will determine appropriate number of significant digits for final answers","Students will understand concepts like population density, area, and rates using scientific notation","Students will justify their answers and assess reasonableness in context"]', '["multi-step problem","population density","significant digits","area","rate","reasonableness"]', '["Whiteboard and markers","Scientific calculator","Student notebooks","Multi-step real-world problem set","Significant digits rules poster"]', 100, 50, 'Level 2: Basic Application of Skills & Concepts', '["MA.K12.MTR.2.1","MA.K12.MTR.4.1","MA.K12.MTR.6.1","MA.K12.MTR.7.1"]', 'NOT CREATED', 'Example: Puerto Rico population 3.98×10^6 people, density 1000 people/sq mi. Find area. Answer: 3.98×10^3 sq mi (3 sig figs).'),
  (14, '2025-10-21', 'B', 'Q1', 1, 'Number Sense and Operations - 8th Grade', 'MA.8.NSO.1.7', 'Solve multi-step mathematical and real-world problems involving the order of operations with rational numbers including exponents and radicals.', 'Number Sense and Operations', 'Order of Operations Review with Integer Exponents and Radicals', '["Students will review the order of operations (Parentheses, Exponents/Radicals, Multiplication/Division, Addition/Subtraction)","Students will understand that radicals act as grouping symbols (evaluate inside first)","Students will simplify square roots of perfect squares up to 225","Students will simplify cube roots of perfect cubes from -125 to 125","Students will evaluate multi-step expressions (up to 6 steps) with exponents and radicals"]', '["order of operations","PEMDAS/GEMDAS","grouping symbols","exponent","radical","square root","cube root","perfect square","perfect cube"]', '["Whiteboard and markers","Calculator","Student notebooks","Perfect squares chart (1-225)","Perfect cubes chart (-125 to 125)","Order of operations reference poster","Practice worksheet with exponents and radicals"]', 100, 50, 'Level 2: Basic Application of Skills & Concepts', '["MA.K12.MTR.2.1","MA.K12.MTR.4.1","MA.K12.MTR.5.1"]', 'NOT CREATED', 'Example: (-1/2)^2 + √(2^3 + 8) = 1/4 + √16 = 1/4 + 4 = 17/4. Avoid PEMDAS mnemonic - use proper grouping and number sense.'),
  (15, '2025-10-24', 'B', 'Q1', 1, 'Number Sense and Operations - 8th Grade', 'MA.8.NSO.1.7', 'Solve multi-step mathematical and real-world problems involving the order of operations with rational numbers including exponents and radicals.', 'Number Sense and Operations', 'Multi-Step Expressions with Rational Numbers, Exponents, and Radicals', '["Students will evaluate expressions with combinations of fractions, decimals, exponents, and radicals","Students will apply order of operations to expressions with up to 6 steps","Students will work with nested grouping symbols and radicals","Students will show equivalence from one step to another in their work","Students will use color-coding or organizational strategies to track multi-step problems"]', '["multi-step expression","nested grouping","equivalence","step-by-step process","simplify"]', '["Whiteboard and markers","Calculator","Student notebooks","Colored pencils or highlighters","Multi-step practice worksheet","Step-by-step solution templates"]', 100, 50, 'Level 2: Basic Application of Skills & Concepts', '["MA.K12.MTR.2.1","MA.K12.MTR.4.1","MA.K12.MTR.5.1"]', 'NOT CREATED', 'Example: ∛27 - 1.4(3^2 - 5) = 3 - 1.4(9-5) = 3 - 1.4(4) = 3 - 5.6 = -2.6. Use color coding for organization.'),
  (16, '2025-10-28', 'B', 'Q1', 1, 'Number Sense and Operations - 8th Grade', 'MA.8.NSO.1.7', 'Solve multi-step mathematical and real-world problems involving the order of operations with rational numbers including exponents and radicals.', 'Number Sense and Operations', 'Real-World Problems Involving Order of Operations with Exponents and Radicals', '["Students will solve real-world problems requiring order of operations with exponents and radicals","Students will apply the Pythagorean Theorem and use square roots in geometric contexts","Students will use area formulas involving squares and cubes (A = s^2, V = s^3)","Students will estimate and predict solutions before solving to check reasonableness","Students will interpret solutions in the context of the problem situation"]', '["real-world application","geometric context","Pythagorean Theorem","area","volume","square root application","reasonableness"]', '["Whiteboard and markers","Calculator","Student notebooks","Real-world task cards (geometry, construction, design contexts)","Three-read strategy cards","Grid paper for diagrams"]', 100, 50, 'Level 2: Basic Application of Skills & Concepts', '["MA.K12.MTR.2.1","MA.K12.MTR.4.1","MA.K12.MTR.6.1","MA.K12.MTR.7.1"]', 'NOT CREATED', 'Example: Dotson backyard problem - total area 600 sq ft, 3 equal squares. Each square area = 200 sq ft, so side = √200 ≈ 14.14 ft. Use three-read strategy.'),
  (17, '2025-10-31', 'B', 'Q1', 1, 'Number Sense and Operations - 8th Grade', 'MA.8.NSO.1.1 - MA.8.NSO.1.7 (Review)', 'Review of all Q1 Standards: Irrational Numbers, Plotting/Comparing, Integer Exponents, Scientific Notation, Order of Operations with Radicals', 'Number Sense and Operations - All Q1 Standards', 'Comprehensive Review - Stations Activity for All Q1 Topics', '["Students will review and demonstrate understanding of irrational numbers and the real number system","Students will plot, order, and compare rational and irrational numbers including square roots and cube roots","Students will apply Laws of Exponents with integer exponents fluently","Students will work with scientific notation: converting, comparing, and performing operations","Students will solve multi-step problems with order of operations including exponents and radicals"]', '[]', '["Whiteboard and markers","Calculator","Student notebooks","Station activity materials (7 stations for 7 standards)","Review game materials (Kahoot or Jeopardy)","Self-assessment checklist"]', 100, 50, 'Level 2: Basic Application of Skills & Concepts', '["MA.K12.MTR.2.1","MA.K12.MTR.4.1","MA.K12.MTR.5.1","MA.K12.MTR.6.1"]', 'NOT CREATED', 'Noon dismissal on Oct 31 - shortened class time. Use station rotation or carousel activity. Quick formative assessment to identify areas needing reteaching.'),
  (18, '2025-11-04', 'B', 'Q1', 1, 'Number Sense and Operations - 8th Grade', 'MA.8.NSO.1.1 - MA.8.NSO.1.7 (Targeted Review and Practice)', 'Targeted Review and Practice - Focus on Challenging Concepts', 'Number Sense and Operations', 'Targeted Practice on Common Misconceptions and Challenging Problems', '["Students will address common misconceptions identified from previous lessons","Students will work through challenging mixed-topic problems","Students will practice explaining their reasoning and solution strategies","Students will engage in peer teaching and collaborative problem solving","Students will demonstrate readiness for the Unit 1 assessment"]', '[]', '["Whiteboard and markers","Calculator","Student notebooks","Error analysis task cards","Challenging problem set","Peer teaching protocols","Exit ticket for self-assessment"]', 100, 50, 'Level 2: Basic Application of Skills & Concepts', '["MA.K12.MTR.2.1","MA.K12.MTR.3.1","MA.K12.MTR.4.1","MA.K12.MTR.5.1","MA.K12.MTR.6.1"]', 'NOT CREATED', 'Focus on areas where students struggled during review. Use error analysis - show incorrect work and have students identify and correct errors. Prepare for assessment.'),
  (19, '2025-11-07', 'B', 'Q1', 1, 'Number Sense and Operations - 8th Grade', 'ASSESSMENT - All Q1 Standards MA.8.NSO.1.1 - MA.8.NSO.1.7', 'Unit 1 Summative Assessment - Number Sense and Operations', 'Number Sense and Operations', 'Unit 1 Summative Assessment', '["Students will demonstrate mastery of all MA.8.NSO.1.1 - MA.8.NSO.1.7 standards","Students will apply knowledge to computational and real-world problems","Students will show work and justify solutions where appropriate","Students will demonstrate procedural fluency with exponents and scientific notation","Students will use appropriate precision and significant digits in answers"]', '[]', '["Assessment booklet","Answer sheet","Calculator","Reference sheet (if allowed)","Scratch paper"]', 100, 50, 'Levels 1-2', '["MA.K12.MTR.2.1","MA.K12.MTR.4.1","MA.K12.MTR.6.1"]', 'NOT CREATED', 'Last day of Q1. Assessment should cover all 7 standards proportionally. Include mix of computational, conceptual, and application problems. Allow calculator use.');

-- ============================================================================
-- Verify data
-- ============================================================================

-- Check total count
DO $$
DECLARE
  lesson_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO lesson_count FROM public.lessons;
  
  IF lesson_count != 87 THEN
    RAISE EXCEPTION 'Expected 87 lessons, but found %', lesson_count;
  ELSE
    RAISE NOTICE 'Successfully seeded % lessons', lesson_count;
  END IF;
END $$;

-- Show summary by quarter
SELECT
  quarter,
  COUNT(*) AS lesson_count,
  MIN(lesson_number) AS first_lesson,
  MAX(lesson_number) AS last_lesson,
  MIN(date) AS start_date,
  MAX(date) AS end_date
FROM public.lessons
GROUP BY quarter
ORDER BY quarter;

-- Show summary by unit
SELECT
  unit_number,
  unit_name,
  COUNT(*) AS lesson_count,
  STRING_AGG(DISTINCT standard_code, ', ' ORDER BY standard_code) AS standards_covered
FROM public.lessons
GROUP BY unit_number, unit_name
ORDER BY unit_number;

